--------------------------------------------
--------------------------------------------

/* EXTRACTION OF INTERVENTIONS GIVEN TO PATIENTS FOLLOWING
THEIR NHSHC CONTACT
*/

--Emma Clegg

--contains:

	-- STEP 1 - Add risk categorisation for each risk factor
	-- STEP 2 - Checks

-- Script uses:
-- 1) Table of attendees/non-attendees with categorised risk factor metrics 
-- at time of NHSHC contact
-- SELECT TOP 10 * FROM [NHS_Health_Checks].[dbo].[EC_4_COHORT_RISK_CATEGORIES]

-- 2) TE lookup table for intervention cluster keys
-- SELECT * FROM [NHS_Health_Checks].[dbo].[TE_LOOKUP_INTERVENTIONS]

-- 3) Cleaned journals table
-- SELECT TOP 10 * FROM [NHS_Health_Checks].[dbo].[JOURNALS_TABLE_CLEANED]

-- 4) Read code lookup table
-- SELECT * FROM [NHS_Health_Checks].[dbo].[EXPANDED_CLUSTERS_REF]

-- Script produces:
-- 1) Table of attendees/non-attendees with intervention information for
-- the 12 months following their NHSHC contact
-- SELECT TOP 10 * FROM [NHS_Health_Checks].[dbo].[EC_5_COHORT_INTERVENTIONS]


/*****************************************************************************/

    --------------------------------------------------------------
	-- STEP 1 - Extract and label intervention codes
    --------------------------------------------------------------

DROP TABLE IF EXISTS #INTERVENTION_CLUSTERS_LONG;

		SELECT B.CLUSTER_JOIN_KEY 
			,B.[INTERVENTION Level 1]
			,A.CLUSTER_DESCRIPTION
			,A.CODE_DESCRIPTION
				    -- Dementia awareness
			,CASE WHEN B.[INTERVENTION Level 1] = 'Dementia awareness' THEN 'DEMENTIA_AWARENESS' 

				-- Support lifestyle - DECLINED
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined'
				      AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%alcohol%'
					  AND A.[CLUSTER_DESCRIPTION] LIKE '%Advice%' THEN 'ADVICE_ALCOHOL_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined'
				      AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%diet%' 
					  AND A.[CLUSTER_DESCRIPTION] LIKE '%Advice%' THEN 'ADVICE_DIET_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined'
				      AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%physical%' 
					  AND A.[CLUSTER_DESCRIPTION] LIKE '%Advice%' THEN 'ADVICE_EXERCISE_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined'
				      AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%smok%' 
					  AND (A.[CLUSTER_DESCRIPTION] LIKE '%Advice%' OR A.[CODE_DESCRIPTION] LIKE '%advice%') THEN 'ADVICE_SMOKING_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined'
				      AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%weight%' 
					  AND A.[CLUSTER_DESCRIPTION] LIKE '%Advice%' THEN 'ADVICE_WEIGHT_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined' 
				   AND A.[CLUSTER_DESCRIPTION] LIKE '%Advice%' THEN 'ADVICE_LIFESTYLE_DECLINED'

                -- Support lifestyle - advice/information
				   WHEN B.[INTERVENTION Level 1] = 'Support Lifestyle'
					AND (B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%Alcohol%'
					   OR B.[CODE_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%alcohol%')
					AND A.[CLUSTER_DESCRIPTION] LIKE '%Advice%' THEN 'ADVICE_ALCOHOL'
				   WHEN B.[INTERVENTION Level 1] = 'Support Lifestyle'
					AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%diet%'
					AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%advice%' THEN 'ADVICE_DIET'
				   WHEN B.[INTERVENTION Level 1] = 'Support Lifestyle'
					AND (B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%Physical%'
					  OR B.[CODE_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%exercise%')
				    AND A.[CLUSTER_DESCRIPTION] LIKE '%Advice%' THEN 'ADVICE_EXERCISE'
				   WHEN B.[INTERVENTION Level 1] = 'Support Lifestyle'
					AND (B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%Smok%'
					   OR B.[CODE_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%Smok%')
				    AND A.[CLUSTER_DESCRIPTION] LIKE '%Advice%'  THEN 'ADVICE_SMOKING'
				   WHEN B.[INTERVENTION Level 1] = 'Support Lifestyle'
					AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%Weight%'
				    AND A.[CLUSTER_DESCRIPTION] LIKE '%Advice%' THEN 'ADVICE_WEIGHT'
				   WHEN B.[INTERVENTION Level 1] = 'Support Lifestyle'
					AND (((B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%lifestyle%' 
					     OR B.[CODE_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%lifestyle%') 
					AND A.[CLUSTER_DESCRIPTION] LIKE '%Advice%')
					OR A.CLUSTER_JOIN_KEY IN (708, 709, 710, 713, 2963, 3095, 3096, 3457))  THEN 'ADVICE_LIFESTYLE'

					-- Further tests
				   WHEN B.[INTERVENTION Level 1] = 'FURTHER TEST'
		                AND A.CLUSTER_DESCRIPTION LIKE '%ACR%' THEN 'FURTHER_TEST_ACR'
				   WHEN B.[INTERVENTION Level 1] = 'FURTHER TEST'
		                AND A.CLUSTER_DESCRIPTION = 'Assessment for Diabetes' THEN 'FURTHER_TEST_DIABETES' 
				   WHEN B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] = 'CVD high risk review declined' THEN 'FURTHER_TEST_CVD_HIGH_RISK_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'FURTHER TEST'
		                AND A.CLUSTER_DESCRIPTION LIKE '%CVD high risk%' THEN 'FURTHER_TEST_CVD_HIGH_RISK'
				   WHEN B.[INTERVENTION Level 1] = 'FURTHER TEST'
		                AND A.CLUSTER_DESCRIPTION LIKE '%CVD risk%' THEN 'FURTHER_TEST_CVD'
				   WHEN B.[INTERVENTION Level 1] = 'FURTHER TEST'
		                AND A.CLUSTER_DESCRIPTION LIKE '%eGFR%'  THEN 'FURTHER_TEST_EGFR'
				   WHEN B.[INTERVENTION Level 1] = 'FURTHER TEST'
		                AND A.CLUSTER_DESCRIPTION LIKE '%GLUCOSE%'
		                AND A.CLUSTER_DESCRIPTION NOT LIKE '%excluding tests%' THEN 'FURTHER_TEST_IGT'

					-- REFERRALS
					WHEN B.[INTERVENTION Level 1] LIKE '%DPP referral declined%' THEN 'DPP_REFERRAL_DECLINED'   
				    WHEN B.[INTERVENTION Level 1] = 'DPP referral' THEN 'DPP_REFERRAL'  
					
					-- Declined referrals
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined' 
				      AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%alcohol%'
					  AND A.[CLUSTER_DESCRIPTION] LIKE '%referral%' THEN 'REFERRAL_ALCOHOL_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined' 
				      AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%diet%' 
					  AND A.[CLUSTER_DESCRIPTION] LIKE '%referral%' THEN 'REFERRAL_DIET_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined' 
				      AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%physical%' 
					  AND A.[CLUSTER_DESCRIPTION] LIKE '%referral%' THEN 'REFERRAL_EXERCISE_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined' 
				      AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%smok%' 
					  AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%refer%' THEN 'REFERRAL_SMOKING_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined' 
				      AND B.[CLUSTER_DESCRIPTION in EMIS VISION MICROTEST] LIKE '%weight%' 
					  AND A.[CLUSTER_DESCRIPTION] LIKE '%referral%' THEN 'REFERRAL_WEIGHT_DECLINED'
				   WHEN B.[INTERVENTION Level 1] = 'Support lifestyle declined' 
				   AND A.[CLUSTER_DESCRIPTION] LIKE '%referral%' THEN 'REFERRAL_LIFESTYLE_DECLINED'
					 
					WHEN B.[INTERVENTION Level 1] = 'FURTHER TEST'
						AND A.CLUSTER_DESCRIPTION LIKE '%diabetes'
						AND A.CLUSTER_DESCRIPTION LIKE '%Referral%' THEN 'REFERRAL_DIABETES'
					WHEN B.[INTERVENTION Level 1] = 'FURTHER TEST'
						AND A.CLUSTER_DESCRIPTION LIKE '%Referral%'
						AND A.CLUSTER_DESCRIPTION LIKE '%IGT%' THEN 'REFERRAL_IGT_IFG'
					WHEN B.[INTERVENTION Level 1] = 'FURTHER TEST'
						AND A.CLUSTER_DESCRIPTION LIKE '%Referral%'
						AND A.CLUSTER_DESCRIPTION LIKE '%ECG%' THEN 'REFERRAL_ECG'

					WHEN [INTERVENTION Level 1] = 'Support lifestyle'
						AND ((CLUSTER_DESCRIPTION LIKE '%Referral%'
						AND CODE_DESCRIPTION LIKE '%Counselling%')
						OR A.CLUSTER_JOIN_KEY IN (714, 715, 796, 3611, 3616, 3687)) THEN 'REFERRAL_LIFESTYLE'
					WHEN [INTERVENTION Level 1] = 'Support lifestyle'
						AND CLUSTER_DESCRIPTION LIKE '%Referral regarding alcohol%' THEN 'REFERRAL_ALCOHOL'
					WHEN [INTERVENTION Level 1] = 'Support lifestyle'
						AND CLUSTER_DESCRIPTION LIKE '%Referral regarding diet%'  THEN 'REFERRAL_DIET'
					WHEN [INTERVENTION Level 1] = 'Support lifestyle'
						AND CLUSTER_DESCRIPTION LIKE '%Referral regarding Physical%'  THEN 'REFERRAL_EXERCISE'
					WHEN [INTERVENTION Level 1] = 'Support lifestyle'
						AND ((CLUSTER_DESCRIPTION = 'Support and refer Stop Smoking Service/Advisor'
						AND CODE_DESCRIPTION NOT LIKE '%advice%')
						OR A.CLUSTER_JOIN_KEY IN (711, 3451))
						 THEN 'REFERRAL_SMOKING'
					WHEN [INTERVENTION Level 1] = 'Support lifestyle'
						AND CLUSTER_DESCRIPTION LIKE '%Referral regarding weight%' THEN 'REFERRAL_WEIGHT'
				    
					ELSE 'OTHER' END AS 'INTERVENTION_TYPE'
			      ,B.CLUSTER_ID
	              
INTO #INTERVENTION_CLUSTERS_LONG
FROM [NHS_Health_Checks].[dbo].[EXPANDED_CLUSTERS_REF] AS A

INNER JOIN [NHS_Health_Checks].[dbo].[TE_LOOKUP_INTERVENTIONS] AS B 
ON A.CLUSTER_JOIN_KEY = B.CLUSTER_JOIN_KEY
;
-- 8,904 records

SELECT * FROM #INTERVENTION_CLUSTERS_LONG
WHERE INTERVENTION_TYPE = 'OTHER'
ORDER BY INTERVENTION_TYPE, CLUSTER_JOIN_KEY

-- Restrict to one label per cluster join key
-- Exclude prescription records
DROP TABLE IF EXISTS #INTERVENTION_CLUSTERS

SELECT *
INTO #INTERVENTION_CLUSTERS
FROM (
	SELECT *
	,ROW_NUMBER() OVER(PARTITION BY CLUSTER_JOIN_KEY ORDER BY CLUSTER_ID) AS 'NO_LABELS'
	FROM #INTERVENTION_CLUSTERS_LONG
	WHERE INTERVENTION_TYPE <> 'OTHER') AS A
WHERE NO_LABELS = 1 
;
-- 243 rows

-- View final lookup table
SELECT * FROM #INTERVENTION_CLUSTERS
ORDER BY INTERVENTION_TYPE, CLUSTER_JOIN_KEY


    --------------------------------------------------------------
	-- STEP 2 - Extract interventions from journals table
    --------------------------------------------------------------

 --- Extract interventions records for all patients from journals table
DROP TABLE IF EXISTS #EC_EXTRACT; 

SELECT 
    A.PATIENT_JOIN_KEY
	,A.[DATE]
	,A.CLUSTER_JOIN_KEY 
	,A.VALUE1_CONDITION
    ,B.[INTERVENTION_TYPE]
		                               
 INTO #EC_EXTRACT
 FROM  [NHS_Health_Checks].[dbo].[JOURNALS_TABLE_CLEANED]  AS A

 INNER JOIN #INTERVENTION_CLUSTERS AS B           -- Join on cluster key lookup
 ON A.CLUSTER_JOIN_KEY = B.CLUSTER_JOIN_KEY

 WHERE A.[PATIENT_JOIN_KEY] IN (SELECT PATIENT_JOIN_KEY                      -- Restrict to attendees/non-attendee population
                                   FROM [NHS_Health_Checks].[dbo].[EC_4_COHORT_RISK_CATEGORIES]  
								   GROUP BY PATIENT_JOIN_KEY)
 AND A.[DATE] IS NOT NULL ;
-- 53,049,900 rows


/* 
Keep one intervention record per patient per day.

Look at the time period between the intervention record and the patient's index date, calculating
DATE_DIFF to represent this.

NOTE: This is intended to introduce duplicate rows as some patients have an NHSHC contact 
in multiple financial years!

*/

DROP TABLE IF EXISTS #EC_EXTRACT2;

SELECT  A.[PATIENT_JOIN_KEY]
  	,B.[DATE] AS 'TEST_DATE'
	,B.[INTERVENTION_TYPE]
	,B.[VALUE1_CONDITION]
	,A.FIN_YEAR
	,A.INDEX_DATE
	,DATEDIFF(day, CONVERT(VARCHAR, A.INDEX_DATE, 23), CONVERT(VARCHAR, B.[DATE], 23)) AS 'DATE_DIFF'
INTO #EC_EXTRACT2

FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES AS A

-- keeps one record per intervention per patient per day
LEFT JOIN (SELECT *
		  ,ROW_NUMBER() OVER (PARTITION BY [PATIENT_JOIN_KEY], [INTERVENTION_TYPE], [DATE] ORDER BY [VALUE1_CONDITION] DESC) AS rn
		  FROM  #EC_EXTRACT) AS B
ON A.PATIENT_JOIN_KEY = B.PATIENT_JOIN_KEY

WHERE B.rn = 1                   -- keep 1 record per intervention per patient per day
GROUP BY A.[PATIENT_JOIN_KEY]
  	,B.[DATE] 
	,B.[INTERVENTION_TYPE]
	,B.[VALUE1_CONDITION]
	,A.FIN_YEAR
	,A.INDEX_DATE;
-- 64,338,128 rows


    --------------------------------------------------------------
	-- STEP 3 - Assign one intervention record per patient on day/after NHSHC (UP TO 12 MTHS AFTER)
    --------------------------------------------------------------

	     -- a. Identify intervention closest to NHSHC index date in each time period

/* Create a table of patients who had an intervention record before their index date
(relevant for non-attendees only) */

DROP TABLE IF EXISTS #EC_INTERVENTION_BEFORE;

SELECT A.[PATIENT_JOIN_KEY]
,A.FIN_YEAR
,A.INDEX_DATE
,A.COHORT
,[INTERVENTION_TYPE] AS 'INT_TYPE_BEFORE'
,[VALUE1_CONDITION] AS 'VAL1_BEFORE'
,[TEST_DATE] AS 'TEST_DATE_BEFORE'
,[DATE_DIFF] AS 'DATE_DIFF_BEFORE' 
INTO #EC_INTERVENTION_BEFORE
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

LEFT JOIN (SELECT * -- this orders by most to least recent date
			  ,ROW_NUMBER() OVER (PARTITION BY [PATIENT_JOIN_KEY], [FIN_YEAR], [INTERVENTION_TYPE] ORDER BY [DATE_DIFF] DESC) AS rn
			  FROM #EC_EXTRACT2
			  WHERE DATE_DIFF < 0
			  ) AS B
ON A.PATIENT_JOIN_KEY = B.PATIENT_JOIN_KEY
AND A.FIN_YEAR = B.FIN_YEAR
AND A.COHORT = 'NON-ATTENDEE' 
AND B.rn = 1

GROUP BY A.[PATIENT_JOIN_KEY]
,A.FIN_YEAR
,A.INDEX_DATE
,A.COHORT
,[INTERVENTION_TYPE]
,[VALUE1_CONDITION]
,[TEST_DATE]
,[DATE_DIFF];
-- 21,298,128 rows


/* Create a table of patients who had an intervention record on their index date */
DROP TABLE IF EXISTS #EC_INTERVENTION_ONDAY;

SELECT A.[PATIENT_JOIN_KEY]
,A.FIN_YEAR
,A.INDEX_DATE
,A.COHORT
,[INTERVENTION_TYPE] AS 'INT_TYPE_ONDAY'
,[VALUE1_CONDITION] AS 'VAL1_ONDAY'
,[TEST_DATE] AS 'TEST_DATE_ONDAY'
,[DATE_DIFF] AS 'DATE_DIFF_ONDAY' 
INTO #EC_INTERVENTION_ONDAY
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

LEFT JOIN (SELECT * 
           FROM #EC_EXTRACT2
		   WHERE DATE_DIFF = 0) AS B
ON A.PATIENT_JOIN_KEY = B.PATIENT_JOIN_KEY
AND A.FIN_YEAR = B.FIN_YEAR

GROUP BY A.[PATIENT_JOIN_KEY]
,A.FIN_YEAR
,A.INDEX_DATE
,A.COHORT
,[INTERVENTION_TYPE]
,[VALUE1_CONDITION]
,[TEST_DATE]
,[DATE_DIFF];
-- 20,284,766 rows


/* Create a table of patients who had an intervention record on the day of their NHSHC */
DROP TABLE IF EXISTS #EC_INTERVENTION_AFTER;

SELECT A.[PATIENT_JOIN_KEY]
,A.FIN_YEAR
,A.INDEX_DATE
,A.COHORT
,[INTERVENTION_TYPE] AS 'INT_TYPE_AFTER'
,[VALUE1_CONDITION] AS 'VAL1_AFTER'
,[TEST_DATE] AS 'TEST_DATE_AFTER'
,[DATE_DIFF] AS 'DATE_DIFF_AFTER' 
INTO #EC_INTERVENTION_AFTER
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

LEFT JOIN (SELECT * -- this orders by closest date to index date
			  ,ROW_NUMBER() OVER (PARTITION BY [PATIENT_JOIN_KEY], [FIN_YEAR], [INTERVENTION_TYPE] ORDER BY [DATE_DIFF]) AS rn
			  FROM #EC_EXTRACT2
			  WHERE DATE_DIFF > 0
			  ) AS B
ON A.PATIENT_JOIN_KEY = B.PATIENT_JOIN_KEY
AND A.FIN_YEAR = B.FIN_YEAR
AND B.rn = 1
AND (A.COHORT = 'NON-ATTENDEE' OR
    (A.COHORT = 'ATTENDEE' AND INTERVENTION_TYPE = 'DEMENTIA_AWARENESS' AND DATE_DIFF <= 7) OR    -- 7 days follow up for demential awareness, otherwise 365 days
	(A.COHORT = 'ATTENDEE' AND DATE_DIFF <= 365))

GROUP BY A.[PATIENT_JOIN_KEY]
,A.FIN_YEAR
,A.INDEX_DATE
,A.COHORT
,[INTERVENTION_TYPE]
,[VALUE1_CONDITION]
,[TEST_DATE]
,[DATE_DIFF];
-- 19,206,159 rows

-- Drop intermediary tables
DROP TABLE IF EXISTS #EC_EXTRACT
DROP TABLE IF EXISTS #EC_EXTRACT2

		 -- b. Separate intervention records into separate fields

/* Left join each of the BEFORE/ON DAY/AFTER tables to the table of patients with 
a completed NHSHC. Intervention fields will be populated only in cases of patients 
having that particular intervention recorded in the corresponding time period. 
*/

------------------------------------------------------------
	-- ADVICE before index date (non-attendees only)
DROP TABLE IF EXISTS #EC_ADVICE_BEFORE2;

SELECT A.[PATIENT_JOIN_KEY]
	,A.FIN_YEAR
	,A.COHORT
	,A.INDEX_DATE
	,B1.INT_TYPE_BEFORE AS 'DEMENTIA_AWARENESS_BEFORE'
	,B2.INT_TYPE_BEFORE AS 'ADVICE_ALCOHOL_BEFORE'
	,B3.INT_TYPE_BEFORE AS 'ADVICE_DIET_BEFORE'
	,B4.INT_TYPE_BEFORE AS 'ADVICE_EXERCISE_BEFORE'
	,B5.INT_TYPE_BEFORE AS 'ADVICE_SMOKING_BEFORE'
	,B6.INT_TYPE_BEFORE AS 'ADVICE_WEIGHT_BEFORE'
	,B7.INT_TYPE_BEFORE AS 'ADVICE_LIFESTYLE_BEFORE'

	,B8.INT_TYPE_BEFORE AS 'ADVICE_ALCOHOL_DECLINED_BEFORE'
	,B9.INT_TYPE_BEFORE AS 'ADVICE_DIET_DECLINED_BEFORE'
	,B10.INT_TYPE_BEFORE AS 'ADVICE_EXERCISE_DECLINED_BEFORE'
	,B11.INT_TYPE_BEFORE AS 'ADVICE_SMOKING_DECLINED_BEFORE'
	,B12.INT_TYPE_BEFORE AS 'ADVICE_WEIGHT_DECLINED_BEFORE'
	,B13.INT_TYPE_BEFORE AS 'ADVICE_LIFESTYLE_DECLINED_BEFORE'
				
INTO #EC_ADVICE_BEFORE2
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

-- ADVICE/INFORMATION 
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'DEMENTIA_AWARENESS') AS B1
ON A.[PATIENT_JOIN_KEY] = B1.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B1.FIN_YEAR

LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_ALCOHOL') AS B2
ON A.[PATIENT_JOIN_KEY] = B2.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B2.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_DIET') AS B3
ON A.[PATIENT_JOIN_KEY] = B3.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B3.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_EXERCISE') AS B4
ON A.[PATIENT_JOIN_KEY] = B4.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B4.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_SMOKING') AS B5
ON A.[PATIENT_JOIN_KEY] = B5.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B5.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_WEIGHT') AS B6
ON A.[PATIENT_JOIN_KEY] = B6.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B6.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_LIFESTYLE') AS B7
ON A.[PATIENT_JOIN_KEY] = B7.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B7.FIN_YEAR

-- ADVICE/INFORMATION - DECLINED
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_ALCOHOL_DECLINED') AS B8
ON A.[PATIENT_JOIN_KEY] = B8.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B8.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_DIET_DECLINED') AS B9
ON A.[PATIENT_JOIN_KEY] = B9.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B9.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_EXERCISE_DECLINED') AS B10
ON A.[PATIENT_JOIN_KEY] = B10.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B10.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_SMOKING_DECLINED') AS B11
ON A.[PATIENT_JOIN_KEY] = B11.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B11.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_WEIGHT_DECLINED') AS B12
ON A.[PATIENT_JOIN_KEY] = B12.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B12.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'ADVICE_LIFESTYLE_DECLINED') AS B13
ON A.[PATIENT_JOIN_KEY] = B13.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B13.FIN_YEAR

;
-- 14,984,656 rows


	-- ADVICE on day of index date
DROP TABLE IF EXISTS #EC_ADVICE_ONDAY2;

SELECT A.[PATIENT_JOIN_KEY]
	,A.FIN_YEAR
	,A.COHORT
	,A.INDEX_DATE
	,B1.INT_TYPE_ONDAY AS 'DEMENTIA_AWARENESS_ONDAY'
	,B2.INT_TYPE_ONDAY AS 'ADVICE_ALCOHOL_ONDAY'
	,B3.INT_TYPE_ONDAY AS 'ADVICE_DIET_ONDAY'
	,B4.INT_TYPE_ONDAY AS 'ADVICE_EXERCISE_ONDAY'
	,B5.INT_TYPE_ONDAY AS 'ADVICE_SMOKING_ONDAY'
	,B6.INT_TYPE_ONDAY AS 'ADVICE_WEIGHT_ONDAY'
	,B7.INT_TYPE_ONDAY AS 'ADVICE_LIFESTYLE_ONDAY'

	,B8.INT_TYPE_ONDAY AS 'ADVICE_ALCOHOL_DECLINED_ONDAY'
	,B9.INT_TYPE_ONDAY AS 'ADVICE_DIET_DECLINED_ONDAY'
	,B10.INT_TYPE_ONDAY AS 'ADVICE_EXERCISE_DECLINED_ONDAY'
	,B11.INT_TYPE_ONDAY AS 'ADVICE_SMOKING_DECLINED_ONDAY'
	,B12.INT_TYPE_ONDAY AS 'ADVICE_WEIGHT_DECLINED_ONDAY'
	,B13.INT_TYPE_ONDAY AS 'ADVICE_LIFESTYLE_DECLINED_ONDAY'
				
INTO #EC_ADVICE_ONDAY2
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

-- ADVICE/INFORMATION 
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'DEMENTIA_AWARENESS') AS B1
ON A.[PATIENT_JOIN_KEY] = B1.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B1.FIN_YEAR

LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_ALCOHOL') AS B2
ON A.[PATIENT_JOIN_KEY] = B2.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B2.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_DIET') AS B3
ON A.[PATIENT_JOIN_KEY] = B3.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B3.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_EXERCISE') AS B4
ON A.[PATIENT_JOIN_KEY] = B4.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B4.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_SMOKING') AS B5
ON A.[PATIENT_JOIN_KEY] = B5.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B5.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_WEIGHT') AS B6
ON A.[PATIENT_JOIN_KEY] = B6.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B6.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_LIFESTYLE') AS B7
ON A.[PATIENT_JOIN_KEY] = B7.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B7.FIN_YEAR

-- ADVICE/INFORMATION - DECLINED
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_ALCOHOL_DECLINED') AS B8
ON A.[PATIENT_JOIN_KEY] = B8.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B8.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_DIET_DECLINED') AS B9
ON A.[PATIENT_JOIN_KEY] = B9.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B9.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_EXERCISE_DECLINED') AS B10
ON A.[PATIENT_JOIN_KEY] = B10.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B10.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_SMOKING_DECLINED') AS B11
ON A.[PATIENT_JOIN_KEY] = B11.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B11.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_WEIGHT_DECLINED') AS B12
ON A.[PATIENT_JOIN_KEY] = B12.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B12.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'ADVICE_LIFESTYLE_DECLINED') AS B13
ON A.[PATIENT_JOIN_KEY] = B13.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B13.FIN_YEAR
;
-- 14,984,656 rows


	-- ADVICE after index date
DROP TABLE IF EXISTS #EC_ADVICE_AFTER2;

SELECT A.[PATIENT_JOIN_KEY]
	,A.FIN_YEAR
	,A.COHORT
	,A.INDEX_DATE
	,B1.INT_TYPE_AFTER AS 'DEMENTIA_AWARENESS_AFTER'
	,B2.INT_TYPE_AFTER AS 'ADVICE_ALCOHOL_AFTER'
	,B3.INT_TYPE_AFTER AS 'ADVICE_DIET_AFTER'
	,B4.INT_TYPE_AFTER AS 'ADVICE_EXERCISE_AFTER'
	,B5.INT_TYPE_AFTER AS 'ADVICE_SMOKING_AFTER'
	,B6.INT_TYPE_AFTER AS 'ADVICE_WEIGHT_AFTER'
	,B7.INT_TYPE_AFTER AS 'ADVICE_LIFESTYLE_AFTER'

	,B8.INT_TYPE_AFTER AS 'ADVICE_ALCOHOL_DECLINED_AFTER'
	,B9.INT_TYPE_AFTER AS 'ADVICE_DIET_DECLINED_AFTER'
	,B10.INT_TYPE_AFTER AS 'ADVICE_EXERCISE_DECLINED_AFTER'
	,B11.INT_TYPE_AFTER AS 'ADVICE_SMOKING_DECLINED_AFTER'
	,B12.INT_TYPE_AFTER AS 'ADVICE_WEIGHT_DECLINED_AFTER'
	,B13.INT_TYPE_AFTER AS 'ADVICE_LIFESTYLE_DECLINED_AFTER'
				
				
INTO #EC_ADVICE_AFTER2
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

-- ADVICE/INFORMATION 
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'DEMENTIA_AWARENESS') AS B1
ON A.[PATIENT_JOIN_KEY] = B1.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B1.FIN_YEAR

LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_ALCOHOL') AS B2
ON A.[PATIENT_JOIN_KEY] = B2.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B2.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_DIET') AS B3
ON A.[PATIENT_JOIN_KEY] = B3.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B3.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_EXERCISE') AS B4
ON A.[PATIENT_JOIN_KEY] = B4.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B4.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_SMOKING') AS B5
ON A.[PATIENT_JOIN_KEY] = B5.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B5.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_WEIGHT') AS B6
ON A.[PATIENT_JOIN_KEY] = B6.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B6.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_LIFESTYLE') AS B7
ON A.[PATIENT_JOIN_KEY] = B7.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B7.FIN_YEAR

-- ADVICE/INFORMATION - DECLINED
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_ALCOHOL_DECLINED') AS B8
ON A.[PATIENT_JOIN_KEY] = B8.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B8.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_DIET_DECLINED') AS B9
ON A.[PATIENT_JOIN_KEY] = B9.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B9.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_EXERCISE_DECLINED') AS B10
ON A.[PATIENT_JOIN_KEY] = B10.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B10.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_SMOKING_DECLINED') AS B11
ON A.[PATIENT_JOIN_KEY] = B11.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B11.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_WEIGHT_DECLINED') AS B12
ON A.[PATIENT_JOIN_KEY] = B12.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B12.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'ADVICE_LIFESTYLE_DECLINED') AS B13
ON A.[PATIENT_JOIN_KEY] = B13.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B13.FIN_YEAR
;
-- 14,984,656 rows


------------------------------------------------------------------
-- REFERRALS before index date (non-attendees only)

DROP TABLE IF EXISTS #EC_REFERRAL_BEFORE2;

SELECT A.[PATIENT_JOIN_KEY]
	,A.FIN_YEAR
	,A.COHORT
	,A.INDEX_DATE
	,B1.INT_TYPE_BEFORE AS 'DPP_REFERRAL_BEFORE'	
	,B2.INT_TYPE_BEFORE AS 'REFERRAL_DIABETES_BEFORE'
	,B3.INT_TYPE_BEFORE AS 'REFERRAL_IGT_IFG_BEFORE'
	,B4.INT_TYPE_BEFORE AS 'REFERRAL_ECG_BEFORE'
	,B5.INT_TYPE_BEFORE AS 'REFERRAL_LIFESTYLE_BEFORE'
	,B6.INT_TYPE_BEFORE AS 'REFERRAL_ALCOHOL_BEFORE'
	,B7.INT_TYPE_BEFORE AS 'REFERRAL_DIET_BEFORE'
	,B8.INT_TYPE_BEFORE AS 'REFERRAL_EXERCISE_BEFORE'
	,B9.INT_TYPE_BEFORE AS 'REFERRAL_SMOKING_BEFORE'
	,B10.INT_TYPE_BEFORE AS 'REFERRAL_WEIGHT_BEFORE'

	,B11.INT_TYPE_BEFORE AS 'DPP_REFERRAL_DECLINED_BEFORE'	
	,B12.INT_TYPE_BEFORE AS 'REFERRAL_ALCOHOL_DECLINED_BEFORE'
	,B13.INT_TYPE_BEFORE AS 'REFERRAL_DIET_DECLINED_BEFORE'
	,B14.INT_TYPE_BEFORE AS 'REFERRAL_EXERCISE_DECLINED_BEFORE'
	,B15.INT_TYPE_BEFORE AS 'REFERRAL_SMOKING_DECLINED_BEFORE'
	,B16.INT_TYPE_BEFORE AS 'REFERRAL_WEIGHT_DECLINED_BEFORE'
				
INTO #EC_REFERRAL_BEFORE2
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

-- DPP
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'DPP_REFERRAL') AS B1
ON A.[PATIENT_JOIN_KEY] = B1.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B1.FIN_YEAR

-- REFERRALS
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_DIABETES') AS B2
ON A.[PATIENT_JOIN_KEY] = B2.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B2.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_IGT_IFG') AS B3
ON A.[PATIENT_JOIN_KEY] = B3.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B3.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_ECG') AS B4
ON A.[PATIENT_JOIN_KEY] = B4.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B4.FIN_YEAR	

LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_LIFESTYLE') AS B5
ON A.[PATIENT_JOIN_KEY] = B5.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B5.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_ALCOHOL') AS B6
ON A.[PATIENT_JOIN_KEY] = B6.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B6.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_DIET') AS B7
ON A.[PATIENT_JOIN_KEY] = B7.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B7.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_EXERCISE') AS B8
ON A.[PATIENT_JOIN_KEY] = B8.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B8.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_SMOKING') AS B9
ON A.[PATIENT_JOIN_KEY] = B9.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B9.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_WEIGHT') AS B10
ON A.[PATIENT_JOIN_KEY] = B10.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B10.FIN_YEAR				

-- DPP DECLINED
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'DPP_REFERRAL_DECLINED') AS B11
ON A.[PATIENT_JOIN_KEY] = B11.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B11.FIN_YEAR

-- REFERRALS DECLINED
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_ALCOHOL_DECLINED') AS B12
ON A.[PATIENT_JOIN_KEY] = B12.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B12.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_DIET_DECLINED') AS B13
ON A.[PATIENT_JOIN_KEY] = B13.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B13.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_EXERCISE_DECLINED') AS B14
ON A.[PATIENT_JOIN_KEY] = B14.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B14.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_SMOKING_DECLINED') AS B15
ON A.[PATIENT_JOIN_KEY] = B15.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B15.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'REFERRAL_WEIGHT_DECLINED') AS B16
ON A.[PATIENT_JOIN_KEY] = B16.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B16.FIN_YEAR				
;
-- 14,984,656 rows


-- REFERRALS on day of index date

DROP TABLE IF EXISTS #EC_REFERRAL_ONDAY2;

SELECT A.[PATIENT_JOIN_KEY]
	,A.FIN_YEAR
	,A.COHORT
	,A.INDEX_DATE
	,B1.INT_TYPE_ONDAY AS 'DPP_REFERRAL_ONDAY'	
	,B2.INT_TYPE_ONDAY AS 'REFERRAL_DIABETES_ONDAY'
	,B3.INT_TYPE_ONDAY AS 'REFERRAL_IGT_IFG_ONDAY'
	,B4.INT_TYPE_ONDAY AS 'REFERRAL_ECG_ONDAY'
	,B5.INT_TYPE_ONDAY AS 'REFERRAL_LIFESTYLE_ONDAY'
	,B6.INT_TYPE_ONDAY AS 'REFERRAL_ALCOHOL_ONDAY'
	,B7.INT_TYPE_ONDAY AS 'REFERRAL_DIET_ONDAY'
	,B8.INT_TYPE_ONDAY AS 'REFERRAL_EXERCISE_ONDAY'
	,B9.INT_TYPE_ONDAY AS 'REFERRAL_SMOKING_ONDAY'
	,B10.INT_TYPE_ONDAY AS 'REFERRAL_WEIGHT_ONDAY'

	,B11.INT_TYPE_ONDAY AS 'DPP_REFERRAL_DECLINED_ONDAY'	
	,B12.INT_TYPE_ONDAY AS 'REFERRAL_ALCOHOL_DECLINED_ONDAY'
	,B13.INT_TYPE_ONDAY AS 'REFERRAL_DIET_DECLINED_ONDAY'
	,B14.INT_TYPE_ONDAY AS 'REFERRAL_EXERCISE_DECLINED_ONDAY'
	,B15.INT_TYPE_ONDAY AS 'REFERRAL_SMOKING_DECLINED_ONDAY'
	,B16.INT_TYPE_ONDAY AS 'REFERRAL_WEIGHT_DECLINED_ONDAY'
				
INTO #EC_REFERRAL_ONDAY2
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

-- DPP
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'DPP_REFERRAL') AS B1
ON A.[PATIENT_JOIN_KEY] = B1.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B1.FIN_YEAR

-- REFERRALS
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_DIABETES') AS B2
ON A.[PATIENT_JOIN_KEY] = B2.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B2.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_IGT_IFG') AS B3
ON A.[PATIENT_JOIN_KEY] = B3.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B3.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_ECG') AS B4
ON A.[PATIENT_JOIN_KEY] = B4.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B4.FIN_YEAR	

LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_LIFESTYLE') AS B5
ON A.[PATIENT_JOIN_KEY] = B5.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B5.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_ALCOHOL') AS B6
ON A.[PATIENT_JOIN_KEY] = B6.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B6.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_DIET') AS B7
ON A.[PATIENT_JOIN_KEY] = B7.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B7.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_EXERCISE') AS B8
ON A.[PATIENT_JOIN_KEY] = B8.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B8.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_SMOKING') AS B9
ON A.[PATIENT_JOIN_KEY] = B9.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B9.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_WEIGHT') AS B10
ON A.[PATIENT_JOIN_KEY] = B10.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B10.FIN_YEAR				

-- DPP DECLINED
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'DPP_REFERRAL_DECLINED') AS B11
ON A.[PATIENT_JOIN_KEY] = B11.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B11.FIN_YEAR

-- REFERRALS DECLINED
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_ALCOHOL_DECLINED') AS B12
ON A.[PATIENT_JOIN_KEY] = B12.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B12.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_DIET_DECLINED') AS B13
ON A.[PATIENT_JOIN_KEY] = B13.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B13.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_EXERCISE_DECLINED') AS B14
ON A.[PATIENT_JOIN_KEY] = B14.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B14.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_SMOKING_DECLINED') AS B15
ON A.[PATIENT_JOIN_KEY] = B15.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B15.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'REFERRAL_WEIGHT_DECLINED') AS B16
ON A.[PATIENT_JOIN_KEY] = B16.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B16.FIN_YEAR		
;
-- 14,984,656 rows

	-- REFERRAL after index date
DROP TABLE IF EXISTS #EC_REFERRAL_AFTER2;

SELECT A.[PATIENT_JOIN_KEY]
	,A.FIN_YEAR
	,A.COHORT
	,A.INDEX_DATE
	,B1.INT_TYPE_AFTER AS 'DPP_REFERRAL_AFTER'	
	,B2.INT_TYPE_AFTER AS 'REFERRAL_DIABETES_AFTER'
	,B3.INT_TYPE_AFTER AS 'REFERRAL_IGT_IFG_AFTER'
	,B4.INT_TYPE_AFTER AS 'REFERRAL_ECG_AFTER'
	,B5.INT_TYPE_AFTER AS 'REFERRAL_LIFESTYLE_AFTER'
	,B6.INT_TYPE_AFTER AS 'REFERRAL_ALCOHOL_AFTER'
	,B7.INT_TYPE_AFTER AS 'REFERRAL_DIET_AFTER'
	,B8.INT_TYPE_AFTER AS 'REFERRAL_EXERCISE_AFTER'
	,B9.INT_TYPE_AFTER AS 'REFERRAL_SMOKING_AFTER'
	,B10.INT_TYPE_AFTER AS 'REFERRAL_WEIGHT_AFTER'

	,B11.INT_TYPE_AFTER AS 'DPP_REFERRAL_DECLINED_AFTER'	
	,B12.INT_TYPE_AFTER AS 'REFERRAL_ALCOHOL_DECLINED_AFTER'
	,B13.INT_TYPE_AFTER AS 'REFERRAL_DIET_DECLINED_AFTER'
	,B14.INT_TYPE_AFTER AS 'REFERRAL_EXERCISE_DECLINED_AFTER'
	,B15.INT_TYPE_AFTER AS 'REFERRAL_SMOKING_DECLINED_AFTER'
	,B16.INT_TYPE_AFTER AS 'REFERRAL_WEIGHT_DECLINED_AFTER'
				
INTO #EC_REFERRAL_AFTER2
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

-- DPP
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'DPP_REFERRAL') AS B1
ON A.[PATIENT_JOIN_KEY] = B1.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B1.FIN_YEAR

-- REFERRALS
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_DIABETES') AS B2
ON A.[PATIENT_JOIN_KEY] = B2.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B2.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_IGT_IFG') AS B3
ON A.[PATIENT_JOIN_KEY] = B3.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B3.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_ECG') AS B4
ON A.[PATIENT_JOIN_KEY] = B4.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B4.FIN_YEAR	

LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_LIFESTYLE') AS B5
ON A.[PATIENT_JOIN_KEY] = B5.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B5.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_ALCOHOL') AS B6
ON A.[PATIENT_JOIN_KEY] = B6.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B6.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_DIET') AS B7
ON A.[PATIENT_JOIN_KEY] = B7.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B7.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_EXERCISE') AS B8
ON A.[PATIENT_JOIN_KEY] = B8.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B8.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_SMOKING') AS B9
ON A.[PATIENT_JOIN_KEY] = B9.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B9.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_WEIGHT') AS B10
ON A.[PATIENT_JOIN_KEY] = B10.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B10.FIN_YEAR				

-- DPP DECLINED
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'DPP_REFERRAL_DECLINED') AS B11
ON A.[PATIENT_JOIN_KEY] = B11.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B11.FIN_YEAR

-- REFERRALS DECLINED
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_ALCOHOL_DECLINED') AS B12
ON A.[PATIENT_JOIN_KEY] = B12.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B12.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_DIET_DECLINED') AS B13
ON A.[PATIENT_JOIN_KEY] = B13.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B13.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_EXERCISE_DECLINED') AS B14
ON A.[PATIENT_JOIN_KEY] = B14.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B14.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_SMOKING_DECLINED') AS B15
ON A.[PATIENT_JOIN_KEY] = B15.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B15.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'REFERRAL_WEIGHT_DECLINED') AS B16
ON A.[PATIENT_JOIN_KEY] = B16.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B16.FIN_YEAR		
;
-- 14,984,656 rows

------------------------------------------------------------------
-- PRESCRIPTIONS AND FURTHER TESTS on day of NHSHC

DROP TABLE IF EXISTS #EC_TESTS_BEFORE2;

SELECT A.[PATIENT_JOIN_KEY]
	,A.FIN_YEAR
	,A.COHORT
	,A.INDEX_DATE
	/*
	,B1.INT_TYPE_BEFORE AS 'PRESCRIPTION_ANTIHYP_BEFORE'																
	,B2.INT_TYPE_BEFORE AS 'PRESCRIPTION_DM_BEFORE'																							
	,B3.INT_TYPE_BEFORE AS 'PRESCRIPTION_OACOAG_BEFORE'
	,B4.INT_TYPE_BEFORE AS 'PRESCRIPTION_STATIN_BEFORE'	
	,B5.INT_TYPE_BEFORE AS 'PRESCRIPTION_OTHER_BEFORE'	
	*/
	,B6.INT_TYPE_BEFORE AS 'FURTHER_TEST_ACR_BEFORE'
	,B7.INT_TYPE_BEFORE AS 'FURTHER_TEST_DIABETES_BEFORE'
	,B8.INT_TYPE_BEFORE AS 'FURTHER_TEST_CVD_HIGH_RISK_BEFORE'
	,B9.INT_TYPE_BEFORE AS 'FURTHER_TEST_CVD_BEFORE'				
	,B10.INT_TYPE_BEFORE AS 'FURTHER_TEST_EGFR_BEFORE'																	
	,B11.INT_TYPE_BEFORE AS 'FURTHER_TEST_IGT_BEFORE'	

	,B12.INT_TYPE_BEFORE AS 'FURTHER_TEST_CVD_HIGH_RISK_DECLINED_BEFORE'
				
INTO #EC_TESTS_BEFORE2
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

/*
-- PRESCRIPTIONS
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'PRESCRIPTION_ANTIHYP') AS B1
ON A.[PATIENT_JOIN_KEY] = B1.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B1.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'PRESCRIPTION_DM') AS B2
ON A.[PATIENT_JOIN_KEY] = B2.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B2.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'PRESCRIPTION_OACOAG') AS B3
ON A.[PATIENT_JOIN_KEY] = B3.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B3.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'PRESCRIPTION_STATIN') AS B4
ON A.[PATIENT_JOIN_KEY] = B4.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B4.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'PRESCRIPTION_OTHER') AS B5
ON A.[PATIENT_JOIN_KEY] = B5.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B5.FIN_YEAR	
*/

-- FURTHER TESTS
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'FURTHER_TEST_ACR') AS B6
ON A.[PATIENT_JOIN_KEY] = B6.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B6.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'FURTHER_TEST_DIABETES') AS B7
ON A.[PATIENT_JOIN_KEY] = B7.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B7.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'FURTHER_TEST_CVD_HIGH_RISK') AS B8
ON A.[PATIENT_JOIN_KEY] = B8.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B8.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'FURTHER_TEST_CVD') AS B9
ON A.[PATIENT_JOIN_KEY] = B9.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B9.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'FURTHER_TEST_EGFR') AS B10
ON A.[PATIENT_JOIN_KEY] = B10.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B10.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'FURTHER_TEST_IGT') AS B11
ON A.[PATIENT_JOIN_KEY] = B11.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B11.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_BEFORE
		   WHERE INT_TYPE_BEFORE = 'FURTHER_TEST_CVD_HIGH_RISK_DECLINED') AS B12
ON A.[PATIENT_JOIN_KEY] = B12.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B12.FIN_YEAR	
;
-- 14,984,656 rows

-- PRESCRIPTIONS AND FURTHER TESTS on day of NHSHC

DROP TABLE IF EXISTS #EC_TESTS_ONDAY2;

SELECT A.[PATIENT_JOIN_KEY]
	,A.FIN_YEAR
	,A.COHORT
	,A.INDEX_DATE
	/*
	,B1.INT_TYPE_ONDAY AS 'PRESCRIPTION_ANTIHYP_ONDAY'																
	,B2.INT_TYPE_ONDAY AS 'PRESCRIPTION_DM_ONDAY'																							
	,B3.INT_TYPE_ONDAY AS 'PRESCRIPTION_OACOAG_ONDAY'
	,B4.INT_TYPE_ONDAY AS 'PRESCRIPTION_STATIN_ONDAY'	
	,B5.INT_TYPE_ONDAY AS 'PRESCRIPTION_OTHER_ONDAY'	
	*/
	,B6.INT_TYPE_ONDAY AS 'FURTHER_TEST_ACR_ONDAY'
	,B7.INT_TYPE_ONDAY AS 'FURTHER_TEST_DIABETES_ONDAY'
	,B8.INT_TYPE_ONDAY AS 'FURTHER_TEST_CVD_HIGH_RISK_ONDAY'
	,B9.INT_TYPE_ONDAY AS 'FURTHER_TEST_CVD_ONDAY'				
	,B10.INT_TYPE_ONDAY AS 'FURTHER_TEST_EGFR_ONDAY'																	
	,B11.INT_TYPE_ONDAY AS 'FURTHER_TEST_IGT_ONDAY'	

	,B12.INT_TYPE_ONDAY AS 'FURTHER_TEST_CVD_HIGH_RISK_DECLINED_ONDAY'
				
INTO #EC_TESTS_ONDAY2
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

/*
-- PRESCRIPTIONS
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'PRESCRIPTION_ANTIHYP') AS B1
ON A.[PATIENT_JOIN_KEY] = B1.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B1.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'PRESCRIPTION_DM') AS B2
ON A.[PATIENT_JOIN_KEY] = B2.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B2.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'PRESCRIPTION_OACOAG') AS B3
ON A.[PATIENT_JOIN_KEY] = B3.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B3.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'PRESCRIPTION_STATIN') AS B4
ON A.[PATIENT_JOIN_KEY] = B4.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B4.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'PRESCRIPTION_OTHER') AS B5
ON A.[PATIENT_JOIN_KEY] = B5.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B5.FIN_YEAR	
*/

-- FURTHER TESTS
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'FURTHER_TEST_ACR') AS B6
ON A.[PATIENT_JOIN_KEY] = B6.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B6.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'FURTHER_TEST_DIABETES') AS B7
ON A.[PATIENT_JOIN_KEY] = B7.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B7.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'FURTHER_TEST_CVD_HIGH_RISK') AS B8
ON A.[PATIENT_JOIN_KEY] = B8.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B8.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'FURTHER_TEST_CVD') AS B9
ON A.[PATIENT_JOIN_KEY] = B9.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B9.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'FURTHER_TEST_EGFR') AS B10
ON A.[PATIENT_JOIN_KEY] = B10.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B10.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'FURTHER_TEST_IGT') AS B11
ON A.[PATIENT_JOIN_KEY] = B11.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B11.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_ONDAY
		   WHERE INT_TYPE_ONDAY = 'FURTHER_TEST_CVD_HIGH_RISK_DECLINED') AS B12
ON A.[PATIENT_JOIN_KEY] = B12.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B12.FIN_YEAR	
;
-- 14,984,656 rows

	-- PRESCRIPTIONS AND FURTHER TESTS after NHSHC
DROP TABLE IF EXISTS #EC_TESTS_AFTER2;

SELECT A.[PATIENT_JOIN_KEY]
	,A.FIN_YEAR
	,A.COHORT
	,A.INDEX_DATE
	/*
	,B1.INT_TYPE_AFTER AS 'PRESCRIPTION_ANTIHYP_AFTER'																
	,B2.INT_TYPE_AFTER AS 'PRESCRIPTION_DM_AFTER'																							
	,B3.INT_TYPE_AFTER AS 'PRESCRIPTION_OACOAG_AFTER'
	,B4.INT_TYPE_AFTER AS 'PRESCRIPTION_STATIN_AFTER'	
	,B5.INT_TYPE_AFTER AS 'PRESCRIPTION_OTHER_AFTER'	
	*/
	,B6.INT_TYPE_AFTER AS 'FURTHER_TEST_ACR_AFTER'
	,B7.INT_TYPE_AFTER AS 'FURTHER_TEST_DIABETES_AFTER'
	,B8.INT_TYPE_AFTER AS 'FURTHER_TEST_CVD_HIGH_RISK_AFTER'
	,B9.INT_TYPE_AFTER AS 'FURTHER_TEST_CVD_AFTER'				
	,B10.INT_TYPE_AFTER AS 'FURTHER_TEST_EGFR_AFTER'																	
	,B11.INT_TYPE_AFTER AS 'FURTHER_TEST_IGT_AFTER'	
	,B12.INT_TYPE_AFTER AS 'FURTHER_TEST_CVD_HIGH_RISK_DECLINED_AFTER'
				
INTO #EC_TESTS_AFTER2
FROM [NHS_Health_Checks].[dbo].EC_4_COHORT_RISK_CATEGORIES  AS A

/*
-- PRESCRIPTIONS
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'PRESCRIPTION_ANTIHYP') AS B1
ON A.[PATIENT_JOIN_KEY] = B1.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B1.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'PRESCRIPTION_DM') AS B2
ON A.[PATIENT_JOIN_KEY] = B2.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B2.FIN_YEAR
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'PRESCRIPTION_OACOAG') AS B3
ON A.[PATIENT_JOIN_KEY] = B3.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B3.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'PRESCRIPTION_STATIN') AS B4
ON A.[PATIENT_JOIN_KEY] = B4.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B4.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'PRESCRIPTION_OTHER') AS B5
ON A.[PATIENT_JOIN_KEY] = B5.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B5.FIN_YEAR	
	*/

-- FURTHER TESTS
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'FURTHER_TEST_ACR') AS B6
ON A.[PATIENT_JOIN_KEY] = B6.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B6.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'FURTHER_TEST_DIABETES') AS B7
ON A.[PATIENT_JOIN_KEY] = B7.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B7.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'FURTHER_TEST_CVD_HIGH_RISK') AS B8
ON A.[PATIENT_JOIN_KEY] = B8.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B8.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'FURTHER_TEST_CVD') AS B9
ON A.[PATIENT_JOIN_KEY] = B9.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B9.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'FURTHER_TEST_EGFR') AS B10
ON A.[PATIENT_JOIN_KEY] = B10.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B10.FIN_YEAR		
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'FURTHER_TEST_IGT') AS B11
ON A.[PATIENT_JOIN_KEY] = B11.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B11.FIN_YEAR	
LEFT JOIN (SELECT * FROM #EC_INTERVENTION_AFTER
		   WHERE INT_TYPE_AFTER = 'FURTHER_TEST_CVD_HIGH_RISK_DECLINED') AS B12
ON A.[PATIENT_JOIN_KEY] = B12.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B12.FIN_YEAR	

;
-- 14,984,656 rows

------------------------------------------------------------------

-- Drop intermediary tables
DROP TABLE IF EXISTS #EC_INTERVENTION_ONDAY
DROP TABLE IF EXISTS #EC_INTERVENTION_AFTER

    --------------------------------------------------------------
	-- STEP 5 - Assign final intervention metrics to patients
    --------------------------------------------------------------

DROP TABLE IF EXISTS #PATIENT_METRICS_INTERVENTIONS;

SELECT * INTO #PATIENT_METRICS_INTERVENTIONS 
FROM (

SELECT 
A.*
				-- ADVICE
				,COALESCE(DEMENTIA_AWARENESS_BEFORE, DEMENTIA_AWARENESS_ONDAY, DEMENTIA_AWARENESS_AFTER) AS DEMENTIA_AWARENESS
				,COALESCE(ADVICE_ALCOHOL_BEFORE, ADVICE_ALCOHOL_ONDAY, ADVICE_ALCOHOL_AFTER) AS ADVICE_ALCOHOL
				,COALESCE(ADVICE_DIET_BEFORE, ADVICE_DIET_ONDAY, ADVICE_DIET_AFTER) AS ADVICE_DIET
				,COALESCE(ADVICE_EXERCISE_BEFORE, ADVICE_EXERCISE_ONDAY, ADVICE_EXERCISE_AFTER) AS ADVICE_EXERCISE
				,COALESCE(ADVICE_SMOKING_BEFORE, ADVICE_SMOKING_ONDAY, ADVICE_SMOKING_AFTER) AS ADVICE_SMOKING
				,COALESCE(ADVICE_WEIGHT_BEFORE, ADVICE_WEIGHT_ONDAY, ADVICE_WEIGHT_AFTER) AS ADVICE_WEIGHT
				,COALESCE(ADVICE_LIFESTYLE_BEFORE, ADVICE_LIFESTYLE_ONDAY, ADVICE_LIFESTYLE_AFTER) AS ADVICE_LIFESTYLE

				,COALESCE(ADVICE_ALCOHOL_DECLINED_BEFORE, ADVICE_ALCOHOL_DECLINED_ONDAY, ADVICE_ALCOHOL_DECLINED_AFTER) AS ADVICE_ALCOHOL_DECLINED
				,COALESCE(ADVICE_DIET_DECLINED_BEFORE, ADVICE_DIET_DECLINED_ONDAY, ADVICE_DIET_DECLINED_AFTER) AS ADVICE_DIET_DECLINED
				,COALESCE(ADVICE_EXERCISE_DECLINED_BEFORE, ADVICE_EXERCISE_DECLINED_ONDAY, ADVICE_EXERCISE_DECLINED_AFTER) AS ADVICE_EXERCISE_DECLINED
				,COALESCE(ADVICE_SMOKING_DECLINED_BEFORE, ADVICE_SMOKING_DECLINED_ONDAY, ADVICE_SMOKING_DECLINED_AFTER) AS ADVICE_SMOKING_DECLINED
				,COALESCE(ADVICE_WEIGHT_DECLINED_BEFORE, ADVICE_WEIGHT_DECLINED_ONDAY, ADVICE_WEIGHT_DECLINED_AFTER) AS ADVICE_WEIGHT_DECLINED
				,COALESCE(ADVICE_LIFESTYLE_DECLINED_BEFORE, ADVICE_LIFESTYLE_DECLINED_ONDAY, ADVICE_LIFESTYLE_DECLINED_AFTER) AS ADVICE_LIFESTYLE_DECLINED

				-- REFERRALS
				,COALESCE(DPP_REFERRAL_BEFORE, DPP_REFERRAL_ONDAY, DPP_REFERRAL_AFTER) AS DPP_REFERRAL
				,COALESCE(REFERRAL_DIABETES_BEFORE, REFERRAL_DIABETES_ONDAY, REFERRAL_DIABETES_AFTER) AS REFERRAL_DIABETES
				,COALESCE(REFERRAL_IGT_IFG_BEFORE, REFERRAL_IGT_IFG_ONDAY, REFERRAL_IGT_IFG_AFTER) AS REFERRAL_IGT_IFG
				,COALESCE(REFERRAL_ECG_BEFORE, REFERRAL_ECG_ONDAY, REFERRAL_ECG_AFTER) AS REFERRAL_ECG
				,COALESCE(REFERRAL_LIFESTYLE_BEFORE, REFERRAL_LIFESTYLE_ONDAY, REFERRAL_LIFESTYLE_AFTER) AS REFERRAL_LIFESTYLE
				,COALESCE(REFERRAL_ALCOHOL_BEFORE, REFERRAL_ALCOHOL_ONDAY, REFERRAL_ALCOHOL_AFTER) AS REFERRAL_ALCOHOL
				,COALESCE(REFERRAL_DIET_BEFORE, REFERRAL_DIET_ONDAY, REFERRAL_DIET_AFTER) AS REFERRAL_DIET
				,COALESCE(REFERRAL_EXERCISE_BEFORE, REFERRAL_EXERCISE_ONDAY, REFERRAL_EXERCISE_AFTER) AS REFERRAL_EXERCISE
				,COALESCE(REFERRAL_SMOKING_BEFORE, REFERRAL_SMOKING_ONDAY, REFERRAL_SMOKING_AFTER) AS REFERRAL_SMOKING
				,COALESCE(REFERRAL_WEIGHT_BEFORE, REFERRAL_WEIGHT_ONDAY, REFERRAL_WEIGHT_AFTER) AS REFERRAL_WEIGHT

				,COALESCE(DPP_REFERRAL_DECLINED_BEFORE, DPP_REFERRAL_DECLINED_ONDAY, DPP_REFERRAL_DECLINED_AFTER) AS DPP_REFERRAL_DECLINED
				,COALESCE(REFERRAL_ALCOHOL_DECLINED_BEFORE, REFERRAL_ALCOHOL_DECLINED_ONDAY, REFERRAL_ALCOHOL_DECLINED_AFTER) AS REFERRAL_ALCOHOL_DECLINED
				,COALESCE(REFERRAL_DIET_DECLINED_BEFORE, REFERRAL_DIET_DECLINED_ONDAY, REFERRAL_DIET_DECLINED_AFTER) AS REFERRAL_DIET_DECLINED
				,COALESCE(REFERRAL_EXERCISE_DECLINED_BEFORE, REFERRAL_EXERCISE_DECLINED_ONDAY, REFERRAL_EXERCISE_DECLINED_AFTER) AS REFERRAL_EXERCISE_DECLINED
				,COALESCE(REFERRAL_SMOKING_DECLINED_BEFORE, REFERRAL_SMOKING_DECLINED_ONDAY, REFERRAL_SMOKING_DECLINED_AFTER) AS REFERRAL_SMOKING_DECLINED
				,COALESCE(REFERRAL_WEIGHT_DECLINED_BEFORE, REFERRAL_WEIGHT_DECLINED_ONDAY, REFERRAL_WEIGHT_DECLINED_AFTER) AS REFERRAL_WEIGHT_DECLINED

				-- PRESCRIPTIONS/FURTHER TESTS
				/*
				,COALESCE(PRESCRIPTION_ANTIHYP_BEFORE, PRESCRIPTION_ANTIHYP_ONDAY, PRESCRIPTION_ANTIHYP_AFTER) AS PRESCRIPTION_ANTIHYP
				,COALESCE(PRESCRIPTION_DM_BEFORE, PRESCRIPTION_DM_ONDAY, PRESCRIPTION_DM_AFTER) AS PRESCRIPTION_DM
				,COALESCE(PRESCRIPTION_OACOAG_BEFORE, PRESCRIPTION_OACOAG_ONDAY, PRESCRIPTION_OACOAG_AFTER) AS PRESCRIPTION_OACOAG
				,COALESCE(PRESCRIPTION_STATIN_BEFORE, PRESCRIPTION_STATIN_ONDAY, PRESCRIPTION_STATIN_AFTER) AS PRESCRIPTION_STATIN
				,COALESCE(PRESCRIPTION_OTHER_BEFORE, PRESCRIPTION_OTHER_ONDAY, PRESCRIPTION_OTHER_AFTER) AS PRESCRIPTION_OTHER
				*/

				,COALESCE(FURTHER_TEST_ACR_BEFORE, FURTHER_TEST_ACR_ONDAY, FURTHER_TEST_ACR_AFTER) AS FURTHER_TEST_ACR
				,COALESCE(FURTHER_TEST_DIABETES_BEFORE, FURTHER_TEST_DIABETES_ONDAY, FURTHER_TEST_DIABETES_AFTER) AS FURTHER_TEST_DIABETES
				,COALESCE(FURTHER_TEST_CVD_HIGH_RISK_BEFORE, FURTHER_TEST_CVD_HIGH_RISK_ONDAY, FURTHER_TEST_CVD_HIGH_RISK_AFTER) AS FURTHER_TEST_CVD_HIGH_RISK
				,COALESCE(FURTHER_TEST_CVD_BEFORE, FURTHER_TEST_CVD_ONDAY, FURTHER_TEST_CVD_AFTER) AS FURTHER_TEST_CVD
				,COALESCE(FURTHER_TEST_EGFR_BEFORE, FURTHER_TEST_EGFR_ONDAY, FURTHER_TEST_EGFR_AFTER) AS FURTHER_TEST_EGFR
				,COALESCE(FURTHER_TEST_IGT_BEFORE, FURTHER_TEST_IGT_ONDAY, FURTHER_TEST_IGT_AFTER) AS FURTHER_TEST_IGT
				,COALESCE(FURTHER_TEST_CVD_HIGH_RISK_DECLINED_BEFORE, FURTHER_TEST_CVD_HIGH_RISK_DECLINED_ONDAY, FURTHER_TEST_CVD_HIGH_RISK_DECLINED_AFTER) AS FURTHER_TEST_CVD_HIGH_RISK_DECLINED

FROM [NHS_Health_Checks].[dbo].[EC_4_COHORT_RISK_CATEGORIES] AS A

LEFT JOIN #EC_ADVICE_BEFORE2 AS B 
ON A.[PATIENT_JOIN_KEY] = B.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = B.FIN_YEAR

LEFT JOIN #EC_ADVICE_ONDAY2 AS C
ON A.[PATIENT_JOIN_KEY] = C.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = C.FIN_YEAR

LEFT JOIN #EC_ADVICE_AFTER2 AS D
ON A.[PATIENT_JOIN_KEY] = D.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = D.FIN_YEAR 


LEFT JOIN #EC_REFERRAL_BEFORE2 AS E
ON A.[PATIENT_JOIN_KEY] = E.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = E.FIN_YEAR

LEFT JOIN #EC_REFERRAL_ONDAY2 AS F
ON A.[PATIENT_JOIN_KEY] = F.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = F.FIN_YEAR

LEFT JOIN #EC_REFERRAL_AFTER2 AS G
ON A.[PATIENT_JOIN_KEY] = G.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = G.FIN_YEAR 


LEFT JOIN #EC_TESTS_BEFORE2 AS H
ON A.[PATIENT_JOIN_KEY] = H.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = H.FIN_YEAR

LEFT JOIN #EC_TESTS_ONDAY2 AS I
ON A.[PATIENT_JOIN_KEY] = I.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = I.FIN_YEAR

LEFT JOIN #EC_TESTS_AFTER2 AS J
ON A.[PATIENT_JOIN_KEY] = J.[PATIENT_JOIN_KEY]
AND A.FIN_YEAR = J.FIN_YEAR 
) AS X;
-- 14,984,656 rows


-- View data
SELECT TOP 10 * FROM #PATIENT_METRICS_INTERVENTIONS;

-- Save to permanent table
DROP TABLE IF EXISTS [NHS_Health_Checks].[dbo].[EC_5_COHORT_INTERVENTIONS];

SELECT *
INTO [NHS_Health_Checks].[dbo].[EC_5_COHORT_INTERVENTIONS]
FROM #PATIENT_METRICS_INTERVENTIONS AS X;
-- 14,984,656 rows


-- View data
SELECT TOP 10 * FROM [NHS_Health_Checks].[dbo].[EC_5_COHORT_INTERVENTIONS] 

-- Drop intermediary tables
DROP TABLE IF EXISTS #EC_EXTRACT;
DROP TABLE IF EXISTS #EC_EXTRACT2;
DROP TABLE IF EXISTS #EC_INTERVENTION_ONDAY;
DROP TABLE IF EXISTS #EC_INTERVENTION_ONDAY2;
DROP TABLE IF EXISTS #EC_INTERVENTION_AFTER;
DROP TABLE IF EXISTS #EC_INTERVENTION_AFTER2;



